### ISSUE TITLE
Continuous integration and docker auto-build

### ISSUE THREAD

**Issue by zhucaoxiang** [PrincetonUniversity/STELLOPT#70]
In the branch `ci`, I have implemented some initial tests for continuous integration (CI). Basically, each push and pull-request will trigger an automatic build and regression test. This could be done with various tools. Here, I am using `GitHub actions` and `Docker`. 

It seems that GitHub action cannot cache numerical packages. To avoid installing all the required packages each time, I created a docker image for compiling (`docker pull zhucaoxiang/stellopt:compile`). When triggered, it will compile the latest code and run testings using the docker image. An example log can be found [here](https://github.com/PrincetonUniversity/STELLOPT/runs/805938442?check_suite_focus=true). It takes 5 minutes to compile the code.
```yaml
name: build-test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zhucaoxiang/stellopt:compile
    env:
      MACHINE: docker
      STELLOPT_PATH: ${{ github.workspace }}
      OMPI_ALLOW_RUN_AS_ROOT: 1
      OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
    steps:
      - name: checkout sources
        uses: actions/checkout@master
      - name: compile
        run: |
          cd ${STELLOPT_PATH}
          ./build_all 2>&1 | tee log.build
      - name: test
        run: |
          cd ${STELLOPT_PATH}/BENCHMARKS
          make test_vmec_QAS
```

Here are the things that I would like to discuss.
- [ ] Are these the right tools to do CI? Does anyone have other experiences? 
- [ ] Decide the appropriate triggers. Should we do the test for every push in every branch? Fortunately, we have unlimited building time.
- [ ] Complete the regression test. Right now, I have only implemented one simple test `compere QAS VMEC case`. We should determine a list of regression tests that are representative and fast. Also, we have to update the check script.
